import Foundation

enum IngredientUnitSuggestions {
    private static let table: [String: String] = [
        // MARK: - Grains, flours, starches, legumes (bulk pantry staples → lb)
        "flour": "cup",
        "all-purpose flour": "cup",
        "whole wheat flour": "cup",
        "atta": "lb",
        "wheat flour": "lb",
        "maida": "lb",
        "besan": "cup",
        "gram flour": "cup",
        "chickpea flour": "cup",
        "rice flour": "cup",
        "semolina": "cup",
        "sooji": "cup",
        "rava": "cup",
        "cornmeal": "cup",
        "cornstarch": "tsp",
        "corn flour": "tsp",
        "arrowroot": "tsp",
        "sugar": "cup",
        "brown sugar": "cup",
        "powdered sugar": "cup",
        "confectioners sugar": "cup",
        "jaggery": "oz",
        "gur": "oz",
        "rice": "lb",
        "basmati rice": "lb",
        "jasmine rice": "lb",
        "brown rice": "lb",
        "white rice": "lb",
        "sona masoori rice": "lb",
        "poha": "cup",
        "flattened rice": "cup",
        "puffed rice": "cup",
        "murmura": "cup",
        "oats": "cup",
        "rolled oats": "cup",
        "steel cut oats": "cup",
        "quinoa": "cup",
        "couscous": "cup",
        "bulgur": "cup",
        "barley": "cup",
        "millet": "cup",
        "ragi": "cup",
        "jowar": "cup",
        "bajra": "cup",
        "bread crumbs": "cup",
        "breadcrumbs": "cup",
        "panko": "cup",
        "pasta": "lb",
        "spaghetti": "lb",
        "penne": "lb",
        "macaroni": "lb",
        "fettuccine": "lb",
        "linguine": "lb",
        "lasagna noodles": "lb",
        "egg noodles": "lb",
        "rice noodles": "lb",
        "vermicelli": "lb",
        "sevai": "lb",
        "soba noodles": "lb",
        "udon noodles": "lb",
        "ramen noodles": "lb",

        "lentils": "cup",
        "red lentils": "cup",
        "masoor dal": "cup",
        "yellow lentils": "cup",
        "toor dal": "cup",
        "arhar dal": "cup",
        "moong dal": "cup",
        "split mung beans": "cup",
        "chana dal": "cup",
        "split chickpeas": "cup",
        "urad dal": "cup",
        "split black lentils": "cup",
        "green lentils": "cup",
        "black lentils": "cup",
        "kala chana": "cup",
        "black chickpeas": "cup",
        "chickpeas": "cup",
        "garbanzo beans": "cup",
        "kidney beans": "cup",
        "rajma": "cup",
        "black beans": "cup",
        "pinto beans": "cup",
        "navy beans": "cup",
        "black eyed peas": "cup",
        "lobia": "cup",
        "split peas": "cup",
        "green peas": "cup",
        "peas": "cup",

        // MARK: - Dairy, liquids
        "milk": "cup",
        "water": "cup",
        "heavy cream": "cup",
        "half and half": "cup",
        "buttermilk": "cup",
        "coconut milk": "cup",
        "coconut cream": "cup",
        "yogurt": "cup",
        "curd": "cup",
        "dahi": "cup",
        "greek yogurt": "cup",
        "sour cream": "cup",
        "broth": "cup",
        "chicken broth": "cup",
        "vegetable broth": "cup",
        "beef broth": "cup",
        "bone broth": "cup",
        "stock": "cup",
        "chicken stock": "cup",
        "coconut water": "cup",

        // MARK: - Oils, fats, condiments (tbsp)
        "olive oil": "tbsp",
        "extra virgin olive oil": "tbsp",
        "vegetable oil": "tbsp",
        "canola oil": "tbsp",
        "sunflower oil": "tbsp",
        "coconut oil": "tbsp",
        "sesame oil": "tbsp",
        "mustard oil": "tbsp",
        "ghee": "tbsp",
        "clarified butter": "tbsp",
        "butter": "tbsp",
        "vegan butter": "tbsp",
        "honey": "tbsp",
        "maple syrup": "tbsp",
        "corn syrup": "tbsp",
        "molasses": "tbsp",
        "soy sauce": "tbsp",
        "tamari": "tbsp",
        "fish sauce": "tbsp",
        "oyster sauce": "tbsp",
        "hoisin sauce": "tbsp",
        "worcestershire sauce": "tbsp",
        "vinegar": "tbsp",
        "balsamic vinegar": "tbsp",
        "apple cider vinegar": "tbsp",
        "rice vinegar": "tbsp",
        "white vinegar": "tbsp",
        "lemon juice": "tbsp",
        "lime juice": "tbsp",
        "tomato paste": "tbsp",
        "tamarind paste": "tbsp",
        "tamarind": "tbsp",
        "imli": "tbsp",
        "mayonnaise": "tbsp",
        "mustard": "tbsp",
        "dijon mustard": "tbsp",
        "ketchup": "tbsp",
        "sriracha": "tbsp",
        "hot sauce": "tbsp",
        "chili garlic sauce": "tbsp",
        "tahini": "tbsp",
        "peanut butter": "tbsp",
        "almond butter": "tbsp",
        "ginger garlic paste": "tbsp",
        "garlic paste": "tbsp",
        "ginger paste": "tbsp",
        "green chutney": "tbsp",
        "mint chutney": "tbsp",
        "tamarind chutney": "tbsp",
        "mango chutney": "tbsp",
        "pickle": "tbsp",
        "achaar": "tbsp",

        // MARK: - Spices, herbs, seasonings (tsp) — Indian-forward
        "salt": "tsp",
        "pepper": "tsp",
        "black pepper": "tsp",
        "white pepper": "tsp",
        "cinnamon": "tsp",
        "cinnamon stick": "whole",
        "cumin": "tsp",
        "cumin seeds": "tsp",
        "jeera": "tsp",
        "coriander": "tsp",
        "coriander seeds": "tsp",
        "ground coriander": "tsp",
        "dhania": "tsp",
        "cilantro": "cup",
        "fresh cilantro": "cup",
        "mustard seeds": "tsp",
        "rai": "tsp",
        "fenugreek seeds": "tsp",
        "methi seeds": "tsp",
        "fenugreek leaves": "tbsp",
        "kasuri methi": "tbsp",
        "dried fenugreek leaves": "tbsp",
        "fennel seeds": "tsp",
        "saunf": "tsp",
        "nigella seeds": "tsp",
        "kalonji": "tsp",
        "carom seeds": "tsp",
        "ajwain": "tsp",
        "asafoetida": "tsp",
        "hing": "tsp",
        "turmeric": "tsp",
        "turmeric powder": "tsp",
        "haldi": "tsp",
        "paprika": "tsp",
        "smoked paprika": "tsp",
        "nutmeg": "tsp",
        "ground nutmeg": "tsp",
        "jaiphal": "tsp",
        "mace": "tsp",
        "javitri": "tsp",
        "baking soda": "tsp",
        "baking powder": "tsp",
        "vanilla extract": "tsp",
        "almond extract": "tsp",
        "chili powder": "tsp",
        "red chili powder": "tsp",
        "kashmiri chili powder": "tsp",
        "cayenne": "tsp",
        "cayenne pepper": "tsp",
        "red pepper flakes": "tsp",
        "crushed red pepper": "tsp",
        "garlic powder": "tsp",
        "onion powder": "tsp",
        "oregano": "tsp",
        "dried oregano": "tsp",
        "basil": "tsp",
        "dried basil": "tsp",
        "fresh basil": "cup",
        "thyme": "tsp",
        "dried thyme": "tsp",
        "fresh thyme": "tbsp",
        "rosemary": "tsp",
        "fresh rosemary": "tbsp",
        "sage": "tsp",
        "bay leaf": "whole",
        "bay leaves": "whole",
        "tej patta": "whole",
        "curry leaves": "sprig",
        "kadi patta": "sprig",
        "garam masala": "tsp",
        "curry powder": "tsp",
        "tandoori masala": "tsp",
        "chaat masala": "tsp",
        "amchur": "tsp",
        "dry mango powder": "tsp",
        "black salt": "tsp",
        "kala namak": "tsp",
        "cardamom": "tsp",
        "green cardamom": "tsp",
        "cardamom pods": "whole",
        "black cardamom": "whole",
        "cloves": "tsp",
        "whole cloves": "tsp",
        "star anise": "whole",
        "sichuan peppercorns": "tsp",
        "poppy seeds": "tsp",
        "khus khus": "tsp",
        "sesame seeds": "tsp",
        "til": "tsp",
        "saffron": "pinch",
        "kesar": "pinch",
        "rose water": "tsp",
        "kewra water": "tsp",
        "food coloring": "tsp",
        "cocoa powder": "tbsp",
        "espresso powder": "tsp",
        "yeast": "tsp",
        "active dry yeast": "tsp",
        "gelatin": "tsp",

        // MARK: - Produce (whole / clove / bunch)
        "eggs": "whole",
        "egg": "whole",
        "egg whites": "whole",
        "egg yolks": "whole",
        "onion": "whole",
        "onions": "whole",
        "red onion": "whole",
        "yellow onion": "whole",
        "shallot": "whole",
        "shallots": "whole",
        "green onion": "whole",
        "scallion": "whole",
        "scallions": "whole",
        "spring onion": "whole",
        "leek": "whole",
        "potato": "whole",
        "potatoes": "whole",
        "sweet potato": "whole",
        "carrot": "whole",
        "carrots": "whole",
        "garlic": "clove",
        "garlic cloves": "clove",
        "ginger": "in",
        "fresh ginger": "in",
        "tomato": "whole",
        "tomatoes": "whole",
        "cherry tomatoes": "cup",
        "diced tomatoes": "can",
        "crushed tomatoes": "can",
        "tomato sauce": "cup",
        "bell pepper": "whole",
        "green bell pepper": "whole",
        "red bell pepper": "whole",
        "jalapeno": "whole",
        "jalapeño": "whole",
        "green chili": "whole",
        "green chilies": "whole",
        "serrano pepper": "whole",
        "thai chili": "whole",
        "cucumber": "whole",
        "zucchini": "whole",
        "eggplant": "whole",
        "brinjal": "whole",
        "okra": "cup",
        "bhindi": "cup",
        "cauliflower": "head",
        "gobi": "head",
        "cabbage": "head",
        "broccoli": "head",
        "spinach": "cup",
        "palak": "cup",
        "kale": "cup",
        "lettuce": "head",
        "mushroom": "cup",
        "mushrooms": "cup",
        "corn": "ear",
        "corn kernels": "cup",
        "avocado": "whole",
        "lemon": "whole",
        "lime": "whole",
        "orange": "whole",
        "apple": "whole",
        "banana": "whole",
        "mango": "whole",
        "pineapple": "whole",
        "raisins": "cup",
        "dates": "cup",
        "cashews": "cup",
        "almonds": "cup",
        "peanuts": "cup",
        "walnuts": "cup",
        "pistachios": "cup",
        "coconut": "cup",
        "shredded coconut": "cup",
        "desiccated coconut": "cup",
        "mint": "cup",
        "fresh mint": "cup",
        "parsley": "cup",
        "fresh parsley": "cup",
        "dill": "cup",

        // MARK: - Meat, poultry, seafood (lb / oz)
        "chicken breast": "lb",
        "chicken thighs": "lb",
        "chicken drumsticks": "lb",
        "chicken wings": "lb",
        "chicken legs": "lb",
        "chicken": "lb",
        "whole chicken": "lb",
        "rotisserie chicken": "lb",
        "ground chicken": "lb",
        "ground beef": "lb",
        "ground turkey": "lb",
        "ground pork": "lb",
        "ground lamb": "lb",
        "ground venison": "lb",
        "beef": "lb",
        "steak": "lb",
        "ribeye": "lb",
        "sirloin": "lb",
        "flank steak": "lb",
        "skirt steak": "lb",
        "brisket": "lb",
        "short ribs": "lb",
        "oxtail": "lb",
        "stew meat": "lb",
        "veal": "lb",
        "venison": "lb",
        "pork": "lb",
        "pork chops": "lb",
        "pork belly": "lb",
        "pork tenderloin": "lb",
        "pork shoulder": "lb",
        "pork ribs": "lb",
        "spare ribs": "lb",
        "lamb": "lb",
        "lamb chops": "lb",
        "mutton": "lb",
        "goat meat": "lb",
        "duck": "lb",
        "duck breast": "lb",
        "quail": "whole",
        "rabbit": "lb",
        "bacon": "oz",
        "sausage": "lb",
        "chorizo": "lb",
        "italian sausage": "lb",
        "ham": "lb",
        "deli ham": "oz",
        "deli turkey": "oz",
        "pepperoni": "oz",
        "salami": "oz",
        "prosciutto": "oz",
        "pancetta": "oz",
        "hot dogs": "whole",
        "turkey": "lb",
        "turkey breast": "lb",
        "shrimp": "lb",
        "prawns": "lb",
        "fish": "lb",
        "salmon": "lb",
        "tilapia": "lb",
        "cod": "lb",
        "halibut": "lb",
        "catfish": "lb",
        "trout": "lb",
        "swordfish": "lb",
        "mahi mahi": "lb",
        "snapper": "lb",
        "sea bass": "lb",
        "mackerel": "lb",
        "tuna": "oz",
        "anchovies": "oz",
        "sardines": "can",
        "crab": "lb",
        "crab meat": "lb",
        "lobster": "lb",
        "scallops": "lb",
        "clams": "lb",
        "mussels": "lb",
        "squid": "lb",
        "calamari": "lb",
        "octopus": "lb",
        "crawfish": "lb",

        // MARK: - Plant proteins, dairy, cheese (oz)
        "tofu": "oz",
        "firm tofu": "oz",
        "silken tofu": "oz",
        "tempeh": "oz",
        "seitan": "oz",
        "edamame": "cup",
        "soya chunks": "cup",
        "soy chunks": "cup",
        "textured vegetable protein": "cup",
        "paneer": "oz",
        "khoya": "oz",
        "mawa": "oz",
        "malai": "tbsp",
        "clotted cream": "tbsp",
        "condensed milk": "cup",
        "evaporated milk": "cup",
        "milk powder": "cup",
        "cheese": "oz",
        "cheddar cheese": "oz",
        "parmesan": "oz",
        "mozzarella": "oz",
        "cream cheese": "oz",
        "ricotta": "oz",
        "feta": "oz",
        "goat cheese": "oz",
        "provolone": "oz",
        "gruyere": "oz",
        "queso fresco": "oz",

        // MARK: - Additional Indian pantry, masalas, dals, grains
        "long pepper": "tsp",
        "pippali": "tsp",
        "shahi jeera": "tsp",
        "black cumin": "tsp",
        "caraway seeds": "tsp",
        "anardana": "tsp",
        "dried pomegranate seeds": "tsp",
        "rock salt": "tsp",
        "sendha namak": "tsp",
        "dry coconut": "cup",
        "copra": "cup",
        "coconut milk powder": "cup",
        "horse gram": "cup",
        "kulith": "cup",
        "moth beans": "cup",
        "matki": "cup",
        "whole moong": "cup",
        "sprouted moong": "cup",
        "roasted chana": "cup",
        "makhana": "cup",
        "fox nuts": "cup",
        "idli rice": "cup",
        "dosa batter": "cup",
        "idli batter": "cup",
        "urad flour": "cup",
        "ragi flour": "cup",
        "jowar flour": "cup",
        "bajra flour": "cup",
        "sambar powder": "tbsp",
        "rasam powder": "tbsp",
        "biryani masala": "tsp",
        "pav bhaji masala": "tsp",
        "chole masala": "tsp",
        "kitchen king masala": "tsp",
        "meat masala": "tsp",
        "fish curry masala": "tsp",
        "goda masala": "tsp",
        "panch phoron": "tsp",
        "vindaloo paste": "tbsp",
        "korma paste": "tbsp",
        "tikka masala paste": "tbsp",
        "tandoori paste": "tbsp",
        "harissa": "tbsp",
        "za'atar": "tsp",
        "sumac": "tsp",
        "berbere": "tsp",
        "ras el hanout": "tsp",
        "chai masala": "tsp",

        // MARK: - Additional vegetables
        "radish": "whole",
        "mooli": "whole",
        "turnip": "whole",
        "beet": "whole",
        "beetroot": "whole",
        "parsnip": "whole",
        "rutabaga": "whole",
        "fennel bulb": "whole",
        "celery": "stalk",
        "celery root": "whole",
        "asparagus": "bunch",
        "artichoke": "whole",
        "brussels sprouts": "cup",
        "snap peas": "cup",
        "snow peas": "cup",
        "green beans": "cup",
        "string beans": "cup",
        "long beans": "cup",
        "drumstick": "whole",
        "moringa": "whole",
        "bottle gourd": "whole",
        "lauki": "whole",
        "bitter gourd": "whole",
        "karela": "whole",
        "ridge gourd": "whole",
        "turai": "whole",
        "pumpkin": "whole",
        "squash": "whole",
        "butternut squash": "whole",
        "acorn squash": "whole",
        "yam": "whole",
        "taro": "whole",
        "arbi": "whole",
        "plantain": "whole",
        "raw banana": "whole",
        "amaranth leaves": "cup",
        "chaulai": "cup",
        "mustard greens": "cup",
        "sarson": "cup",
        "collard greens": "cup",
        "swiss chard": "cup",
        "arugula": "cup",
        "watercress": "cup",
        "bok choy": "head",
        "napa cabbage": "head",
        "red cabbage": "head",
        "iceberg lettuce": "head",
        "romaine lettuce": "head",
        "endive": "head",

        // MARK: - Fruits
        "papaya": "whole",
        "guava": "whole",
        "pomegranate": "whole",
        "watermelon": "whole",
        "cantaloupe": "whole",
        "honeydew": "whole",
        "kiwi": "whole",
        "peach": "whole",
        "pear": "whole",
        "plum": "whole",
        "apricot": "whole",
        "fig": "whole",
        "grapes": "cup",
        "strawberries": "cup",
        "blueberries": "cup",
        "raspberries": "cup",
        "blackberries": "cup",
        "cranberries": "cup",
        "cherries": "cup",
        "lychee": "cup",
        "dragon fruit": "whole",
        "persimmon": "whole",
        "starfruit": "whole",
        "passionfruit": "whole",
        "jackfruit": "cup",
        "custard apple": "whole",
        "sitaphal": "whole",

        // MARK: - Nuts, seeds
        "pine nuts": "cup",
        "hazelnuts": "cup",
        "brazil nuts": "cup",
        "macadamia nuts": "cup",
        "pecans": "cup",
        "chia seeds": "tbsp",
        "flax seeds": "tbsp",
        "flaxseed meal": "tbsp",
        "hemp seeds": "tbsp",
        "sunflower seeds": "cup",
        "pumpkin seeds": "cup",
        "pepitas": "cup",
        "melon seeds": "cup",
        "magaz": "cup",

        // MARK: - Baking, canned goods, beverages used as ingredients
        "chocolate chips": "cup",
        "dark chocolate": "oz",
        "milk chocolate": "oz",
        "white chocolate": "oz",
        "cocoa nibs": "cup",
        "baking chocolate": "oz",
        "shortening": "cup",
        "lard": "cup",
        "margarine": "tbsp",
        "cream of tartar": "tsp",
        "xanthan gum": "tsp",
        "agar agar": "tsp",
        "pectin": "tsp",
        "instant coffee": "tsp",
        "tea leaves": "tsp",
        "green tea": "tsp",
        "black tea": "tsp",
        "canned corn": "cup",
        "canned beans": "can",
        "coconut flakes": "cup",
        "olives": "cup",
        "capers": "tbsp",
        "sun-dried tomatoes": "cup",
        "roasted red peppers": "cup",
        "pickled ginger": "tbsp",
        "kimchi": "cup",
        "sauerkraut": "cup",
        "wine": "cup",
        "red wine": "cup",
        "white wine": "cup",
        "beer": "cup",
        "rum": "tbsp",
        "brandy": "tbsp",
        "sake": "tbsp",
        "mirin": "tbsp",
        "dashi": "cup",

        // MARK: - Breads, doughs, sauces, spreads
        "self-rising flour": "cup",
        "cake flour": "cup",
        "bread flour": "cup",
        "pizza dough": "lb",
        "pie crust": "whole",
        "tortillas": "whole",
        "corn tortillas": "whole",
        "flour tortillas": "whole",
        "naan": "whole",
        "roti": "whole",
        "chapati": "whole",
        "pita bread": "whole",
        "bread": "loaf",
        "baguette": "whole",
        "sandwich bread": "loaf",
        "hamburger buns": "whole",
        "hot dog buns": "whole",
        "english muffins": "whole",
        "bagels": "whole",
        "croutons": "cup",
        "pesto": "tbsp",
        "alfredo sauce": "cup",
        "marinara sauce": "cup",
        "pasta sauce": "cup",
        "bbq sauce": "tbsp",
        "teriyaki sauce": "tbsp",
        "salsa": "cup",
        "guacamole": "cup",
        "nutella": "tbsp",
        "jam": "tbsp",
        "jelly": "tbsp",
        "apple sauce": "cup",
        "nutritional yeast": "tbsp",
        "vital wheat gluten": "tbsp",
        "instant yeast": "tsp",
        "vanilla bean": "whole",
        "orange zest": "tsp",
        "lemon zest": "tsp",
        "lime zest": "tsp",
        "orange juice": "cup",
        "apple juice": "cup",
        "cranberry juice": "cup",
        "ginger ale": "cup",
        "club soda": "cup",
        "sparkling water": "cup",

        // MARK: - Additional seasoning blends, sweeteners
        "allspice": "tsp",
        "juniper berries": "tsp",
        "chives": "tbsp",
        "tarragon": "tsp",
        "marjoram": "tsp",
        "herbes de provence": "tsp",
        "chinese five spice": "tsp",
        "old bay seasoning": "tsp",
        "italian seasoning": "tsp",
        "taco seasoning": "tbsp",
        "ranch seasoning": "tbsp",
        "poultry seasoning": "tsp",
        "pumpkin pie spice": "tsp",
        "apple pie spice": "tsp",
        "everything bagel seasoning": "tbsp",
        "date syrup": "tbsp",
        "agave nectar": "tbsp",
        "stevia": "tsp",
        "monk fruit sweetener": "tsp",
        "erythritol": "cup",
        "coconut sugar": "cup",
        "demerara sugar": "cup",
        "caster sugar": "cup",
        "turbinado sugar": "cup",
    ]

    /// Every distinct unit used in the suggestions table, common ones first, for use in a picker.
    static let allUnits: [String] = {
        let priority = [
            "cup", "tbsp", "tsp", "lb", "oz", "whole", "clove", "pinch",
            "sprig", "head", "ear", "can", "in", "loaf", "bunch", "stalk",
        ]
        let known = Set(table.values)
        let ordered = priority.filter { known.contains($0) }
        let remaining = known.subtracting(priority).sorted()
        return ordered + remaining
    }()

    static func suggestedUnit(for ingredientName: String) -> String? {
        let name = ingredientName.lowercased().trimmingCharacters(in: .whitespaces)
        guard !name.isEmpty else { return nil }

        if let exact = table[name] {
            return exact
        }

        let matches = table.keys.filter { name.contains($0) }
        return matches.max(by: { $0.count < $1.count }).flatMap { table[$0] }
    }
}
